### ISSUE TITLE
[1.19.2] [Console Error] 

### ISSUE THREAD

**Issue by suerion** [Tschipcraft/spawnanimations#7]
### Describe the bug

Hey, we got on Startup of our Server this Error -> Is there a problem With the 1.19.2 version?

### Additional context

```
[20:15:06] [main/ERROR]: Failed to load function spawnanimations:internal/hidden/trigger_damage/1_19_4
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 3: Incorrect argument for command at position 60: ...n execute <--[HERE]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 3: Incorrect argument for command at position 60: ...n execute <--[HERE]
	at net.minecraft.class_2158.method_9195(class_2158.java:63) ~[server-intermediary.jar:?]
	at net.minecraft.class_5349.method_29451(class_5349.java:85) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
```

**Comment by Tschipcraft** [comment]
Minecraft 1.19.4 introduced the new sub-command `/execute on attacker` which allows Spawn Animations to check if a mob was hurt faster than in previous versions. In 1.19.2, Minecraft throws the error you are seeing here because it doesn't understand the new syntax. For backwards compatibility I added a fallback method which does the same thing and the data pack switches to it by itself if it detects a version below 1.19.4. You can safely ignore the error in the console.

**Comment by suerion** [comment]
okey thanks for the info ;)
