### ISSUE TITLE
1.20 numerous errors on startup

### ISSUE THREAD

**Issue by djoveryde** [Tschipcraft/spawnanimations#9]
### Describe the bug

I'm running the newest version of spawn animations v.1.9 on paper 1.20 and have the following errors when loading the server up.

[15:28:31 ERROR]: Couldn't parse element predicates:spawnanimations:trigger
com.google.gson.JsonSyntaxException: Unknown type 'minecraft:alternative'
at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:95) ~[?:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
at net.minecraft.world.level.storage.loot.LootDataType.lambda$createSingleOrMultipleDeserialiser$2(LootDataType.java:74) ~[paper-1.20.jar:git-Paper-4]
at net.minecraft.world.level.storage.loot.LootDataType.deserialize(LootDataType.java:45) ~[paper-1.20.jar:git-Paper-4]
at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$4(LootDataManager.java:68) ~[paper-1.20.jar:git-Paper-4]
at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$5(LootDataManager.java:67) ~[paper-1.20.jar:git-Paper-4]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:28:31 ERROR]: Couldn't parse element predicates:spawnanimations:has_effect
com.google.gson.JsonSyntaxException: Unknown type 'minecraft:alternative'
at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:95) ~[?:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
at net.minecraft.world.level.storage.loot.LootDataType.lambda$createSingleOrMultipleDeserialiser$2(LootDataType.java:74) ~[paper-1.20.jar:git-Paper-4]
at net.minecraft.world.level.storage.loot.LootDataType.deserialize(LootDataType.java:45) ~[paper-1.20.jar:git-Paper-4]
at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$4(LootDataManager.java:68) ~[paper-1.20.jar:git-Paper-4]
at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$5(LootDataManager.java:67) ~[paper-1.20.jar:git-Paper-4]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:28:31 ERROR]: Couldn't parse element predicates:spawnanimations:exclude
com.google.gson.JsonSyntaxException: Unknown type 'minecraft:alternative'
at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:95) ~[?:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
at net.minecraft.world.level.storage.loot.LootDataType.lambda$createSingleOrMultipleDeserialiser$2(LootDataType.java:74) ~[paper-1.20.jar:git-Paper-4]
at net.minecraft.world.level.storage.loot.LootDataType.deserialize(LootDataType.java:45) ~[paper-1.20.jar:git-Paper-4]
at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$4(LootDataManager.java:68) ~[paper-1.20.jar:git-Paper-4]
at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$5(LootDataManager.java:67) ~[paper-1.20.jar:git-Paper-4]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to reproduce

Add v1.9 datapack on a paper 1.20 server, then load up

**Comment by Tschipcraft** [comment]
Oh... I somehow missed this when I tested Spawn Animations in Minecraft 1.20. It should work fine for the time being, as only the exclusion criteria are affected, but it definitely doesn't fully work. Thanks for letting me know! A fix is on the way
